# Generated by Django 3.1.5 on 2021-01-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=40)),
                ('psuPonderado', models.IntegerField()),
                ('NEM', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('creditos', models.IntegerField()),
                ('prerrequsitos', models.CharField(max_length=30)),
                ('equivalencias', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('nroCorrelativo', models.IntegerField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('semestre', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agno', models.IntegerField()),
                ('carrera', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('codigoSeccion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=8)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.asignatura')),
            ],
            options={
                'unique_together': {('codigoSeccion', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='NodoSeccion',
            fields=[
                ('seccion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generador_horarios.seccion')),
                ('ss', models.IntegerField()),
            ],
            bases=('generador_horarios.seccion',),
        ),
        migrations.CreateModel(
            name='NodoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holgura', models.IntegerField()),
                ('EF', models.IntegerField()),
                ('ES', models.IntegerField()),
                ('LS', models.IntegerField()),
                ('LF', models.IntegerField()),
                ('CC', models.IntegerField()),
                ('UU', models.IntegerField()),
                ('KK', models.IntegerField()),
                ('box', models.ManyToManyField(to='generador_horarios.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('dia', models.CharField(max_length=3)),
                ('modulo', models.CharField(max_length=15)),
                ('profesor', models.CharField(max_length=30)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='mallacurricular',
            field=models.ManyToManyField(to='generador_horarios.MallaCurricular'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='box',
            field=models.ManyToManyField(to='generador_horarios.Box'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='mallacurricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.mallacurricular'),
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='generador_horarios.horario')),
                ('nodoseccion', models.ManyToManyField(to='generador_horarios.NodoSeccion')),
            ],
        ),
        migrations.AddField(
            model_name='nodoseccion',
            name='nodoasignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.nodoasignatura'),
        ),
        migrations.CreateModel(
            name='AsignaturaCursada',
            fields=[
                ('seccion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generador_horarios.seccion')),
                ('nota', models.FloatField()),
                ('estado', models.CharField(max_length=15)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.alumno')),
            ],
            bases=('generador_horarios.seccion',),
        ),
    ]
