# Generated by Django 3.1.5 on 2021-02-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=12)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('token', models.CharField(default=None, max_length=30)),
                ('psu_matematicas', models.IntegerField(default=0)),
                ('psu_lenguaje', models.IntegerField(default=0)),
                ('psu_historia', models.IntegerField(default=0)),
                ('psu_ciencias', models.IntegerField(default=0)),
                ('nem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='asignatura_real',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.IntegerField()),
                ('abre', models.ManyToManyField(related_name='_asignatura_real_abre_+', to='generador_horarios.asignatura_real')),
                ('equivale', models.ManyToManyField(related_name='_asignatura_real_equivale_+', to='generador_horarios.asignatura_real')),
                ('prerrequisito', models.ManyToManyField(related_name='_asignatura_real_prerrequisito_+', to='generador_horarios.asignatura_real')),
            ],
        ),
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correlativo', models.IntegerField()),
                ('semestre', models.CharField(max_length=10)),
                ('to_asignatura_real', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.asignatura_real')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('semestre', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('to_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='malla_curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agno', models.IntegerField()),
                ('carrera', models.CharField(max_length=60)),
                ('json_malla', models.JSONField()),
                ('to_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.box')),
            ],
            options={
                'unique_together': {('agno', 'carrera')},
            },
        ),
        migrations.CreateModel(
            name='nodo_asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holgura', models.IntegerField()),
                ('ef', models.IntegerField()),
                ('es', models.IntegerField()),
                ('ls', models.IntegerField()),
                ('lf', models.IntegerField()),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('to_alumno', models.ManyToManyField(to='generador_horarios.alumno')),
                ('to_asignatura_real', models.ManyToManyField(to='generador_horarios.asignatura_real')),
                ('to_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.box')),
            ],
        ),
        migrations.CreateModel(
            name='nodo_seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss', models.IntegerField()),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='solucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mod', models.DateTimeField()),
                ('to_horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.horario')),
                ('to_nodo_seccion', models.ManyToManyField(to='generador_horarios.nodo_seccion')),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_seccion', models.CharField(max_length=25)),
                ('semestre', models.CharField(max_length=10)),
                ('num_seccion', models.IntegerField()),
                ('to_asignatura_real', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.asignatura_real')),
            ],
            options={
                'unique_together': {('cod_seccion', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='ramo_por_tomar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.IntegerField()),
                ('uu', models.IntegerField()),
                ('kk', models.IntegerField()),
                ('to_asignatura_real', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.asignatura_real')),
                ('to_nodo_asignatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.nodo_asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='oferta_malla',
            fields=[
                ('semestre', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('json_oferta', models.JSONField()),
                ('to_malla_curricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.malla_curricular')),
            ],
        ),
        migrations.AddField(
            model_name='nodo_seccion',
            name='to_ramo_por_tomar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.ramo_por_tomar'),
        ),
        migrations.AddField(
            model_name='nodo_seccion',
            name='to_seccion',
            field=models.ManyToManyField(to='generador_horarios.seccion'),
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('dia', models.CharField(max_length=3)),
                ('modulo', models.CharField(max_length=20)),
                ('profesor', models.CharField(max_length=50)),
                ('to_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='avance_academico',
            fields=[
                ('semestre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('json_avance', models.JSONField()),
                ('fgd_count', models.IntegerField(default=0)),
                ('cfg_count', models.IntegerField(default=0)),
                ('einf_count', models.IntegerField(default=0)),
                ('etele_count', models.IntegerField(default=0)),
                ('to_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='asignatura_cursada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nota', models.FloatField()),
                ('estado', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('to_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.alumno')),
                ('to_avance_academico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.avance_academico')),
                ('to_box', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.box')),
            ],
        ),
    ]
