# Generated by Django 3.1.5 on 2021-02-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura_real',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.IntegerField()),
                ('nro_correlativo', models.CharField(max_length=30)),
                ('semestre', models.CharField(max_length=30)),
                ('tipo', models.IntegerField(default=0)),
                ('equivale', models.ManyToManyField(default=None, related_name='_asignatura_real_equivale_+', to='generador_horarios.asignatura_real')),
                ('prerrequisito', models.ManyToManyField(related_name='_asignatura_real_prerrequisito_+', to='generador_horarios.asignatura_real')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('semestre', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='malla_curricular',
            fields=[
                ('agno', models.IntegerField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=60)),
                ('json_malla', models.JSONField(default=None)),
                ('to_asignatura_real', models.ManyToManyField(to='generador_horarios.asignatura_real')),
                ('to_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agno', 'carrera')},
            },
        ),
        migrations.CreateModel(
            name='nodo_asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holgura', models.IntegerField(default=0)),
                ('ef', models.IntegerField(default=0)),
                ('es', models.IntegerField(default=0)),
                ('ls', models.IntegerField(default=0)),
                ('lf', models.IntegerField(default=0)),
                ('cc', models.CharField(default='0', max_length=3)),
                ('uu', models.CharField(default='0', max_length=3)),
                ('kk', models.CharField(default='0', max_length=3)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('critico', models.BooleanField(default=False)),
                ('to_asignatura_real', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.asignatura_real')),
                ('to_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nodo_seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss', models.CharField(max_length=3)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('to_nodo_asignatura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.nodo_asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='solucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mod', models.DateTimeField()),
                ('to_horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.horario')),
                ('to_nodo_seccion', models.ManyToManyField(to='generador_horarios.nodo_seccion')),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('cod_seccion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=10)),
                ('num_seccion', models.CharField(max_length=20)),
                ('vacantes', models.IntegerField(default=0)),
                ('inscritos', models.IntegerField(default=0)),
                ('vacantes_libres', models.IntegerField(default=0)),
                ('to_asignatura_real', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.asignatura_real')),
            ],
            options={
                'unique_together': {('cod_seccion', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='oferta_malla',
            fields=[
                ('semestre', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('json_oferta', models.JSONField()),
                ('to_malla_curricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.malla_curricular')),
            ],
        ),
        migrations.AddField(
            model_name='nodo_seccion',
            name='to_seccion',
            field=models.ManyToManyField(to='generador_horarios.seccion'),
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('dia', models.CharField(max_length=3)),
                ('modulo', models.CharField(max_length=20)),
                ('profesor', models.CharField(max_length=50)),
                ('to_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='avance_academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('json_avance', models.JSONField(default=dict)),
                ('fgd_count', models.IntegerField(default=0)),
                ('cfg_count', models.IntegerField(default=0)),
                ('einf_count', models.IntegerField(default=0)),
                ('etele_count', models.IntegerField(default=0)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('semestre', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='asignatura_cursada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nota', models.FloatField(default=0)),
                ('estado', models.CharField(max_length=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('to_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_asignatura_real', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generador_horarios.asignatura_real')),
                ('to_avance_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.avance_academico')),
            ],
        ),
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('agno_ingreso', models.IntegerField(default=0)),
                ('psu_matematicas', models.IntegerField(default=0)),
                ('psu_lenguaje', models.IntegerField(default=0)),
                ('psu_historia', models.IntegerField(default=0)),
                ('psu_ciencias', models.IntegerField(default=0)),
                ('nem', models.IntegerField(default=0)),
                ('agno_malla', models.IntegerField(default=0)),
                ('to_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
