# Generated by Django 3.1.5 on 2021-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura_cursada',
            name='nota',
            field=models.FloatField(default=0),
        ),
    ]
