# Generated by Django 3.1.5 on 2021-02-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='to_asignatura_real',
        ),
        migrations.AddField(
            model_name='seccion',
            name='to_asignatura_real',
            field=models.ManyToManyField(to='generador_horarios.asignatura_real'),
        ),
    ]
