# Generated by Django 3.1.5 on 2021-01-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodoasignatura',
            name='box',
        ),
        migrations.AddField(
            model_name='nodoasignatura',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.box'),
        ),
    ]
