# Generated by Django 3.1.5 on 2021-01-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0002_auto_20210126_2237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together=set(),
        ),
    ]
