# Generated by Django 3.1.5 on 2021-02-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0002_asignatura_real_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura_real',
            name='nro_correlativo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asignatura_real',
            name='semestre',
            field=models.CharField(max_length=30),
        ),
    ]
