# Generated by Django 3.1.5 on 2021-02-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0002_auto_20210216_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
