# Generated by Django 3.1.5 on 2021-02-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0003_auto_20210218_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo_asignatura',
            name='critico',
            field=models.BooleanField(default=False),
        ),
    ]
