# Generated by Django 3.1.5 on 2021-01-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0003_auto_20210126_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='NEM',
            new_name='nem',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='psuPonderado',
            new_name='psu_ponderado',
        ),
        migrations.RenameField(
            model_name='asignaturacursada',
            old_name='fechaModificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='nroCorrelativo',
            new_name='nro_correlativo',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='CC',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='EF',
            new_name='ef',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='ES',
            new_name='es',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='KK',
            new_name='kk',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='LF',
            new_name='lf',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='LS',
            new_name='ls',
        ),
        migrations.RenameField(
            model_name='nodoasignatura',
            old_name='UU',
            new_name='uu',
        ),
        migrations.RenameField(
            model_name='nodoseccion',
            old_name='nodoasignatura',
            new_name='nodo_asignatura',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='codigoSeccion',
            new_name='codigo_seccion',
        ),
        migrations.RenameField(
            model_name='solucion',
            old_name='nodoseccion',
            new_name='nodo_seccion',
        ),
    ]
