# Generated by Django 3.1.5 on 2021-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0004_nodo_asignatura_critico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance_academico',
            name='json_avance',
            field=models.JSONField(default=list),
        ),
    ]
