# Generated by Django 3.1.5 on 2021-02-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0004_auto_20210221_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura_real',
            name='importancia',
            field=models.IntegerField(default=0),
        ),
    ]
