# Generated by Django 3.1.5 on 2021-02-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0006_auto_20210219_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo_por_tomar',
            name='cc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ramo_por_tomar',
            name='kk',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ramo_por_tomar',
            name='uu',
            field=models.CharField(max_length=3),
        ),
    ]
