# Generated by Django 3.1.5 on 2021-02-20 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0007_auto_20210219_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodo_seccion',
            name='to_ramo_por_tomar',
        ),
        migrations.AddField(
            model_name='nodo_asignatura',
            name='cc',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='nodo_asignatura',
            name='kk',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='nodo_asignatura',
            name='uu',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='nodo_seccion',
            name='to_nodo_asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generador_horarios.nodo_asignatura'),
        ),
        migrations.DeleteModel(
            name='ramo_por_tomar',
        ),
    ]
