# Generated by Django 3.1.5 on 2021-02-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0008_auto_20210220_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo_seccion',
            name='ss',
            field=models.CharField(max_length=3),
        ),
    ]
