# Generated by Django 3.1.5 on 2021-02-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador_horarios', '0008_asignatura_real_importancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura_real',
            name='importancia',
        ),
    ]
